# Módulo que fica na parte debaixo.

esphome:
  name: piscina_luzes_2
  platform: ESP32
  board: esp32doit-devkit-v1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: piscina_luzes_2
    password: !secret wifi_password

captive_portal:

api:

logger:

ota:
  safe_mode: true
  password: animal
  
switch:
  - platform: gpio
    name: "Piscina - LED - Ilha"
    id: piscina_luzes_gourmet_pia
    pin: GPIO15

  - platform: gpio
    name: "Piscina - LED - Arquibancada"
    id: piscina_luzes_gourmet_led_teto
    pin: GPIO02

  - platform: gpio
    name: "Piscina - Luzes - Gourmet - LED Mesa"
    id: piscina_luzes_gourmet_led_mesa
    pin: GPIO16

  - platform: gpio
    name: "Piscina - Luzes - Gourmet - Ilha"
    id: piscina_luzes_gourmet_ilha
    pin: GPIO17

  - platform: gpio
    name: "Piscina - Luzes - Banheiro - Chuveiro"
    id: piscina_luzes_banheiro_chuveiro
    pin: GPIO05

  - platform: gpio
    name: "Piscina - Luzes - Banheiro - Espelho"
    id: piscina_luzes_banheiro_espelho
    pin: GPIO18

  - platform: gpio
    name: "Piscina - Luzes - Cobertura - Arandelas"
    id: piscina_luzes_cobertura_arandelas
    pin: GPIO19

  - platform: gpio
    name: "Piscina - Luzes - Cobertura - Pergolado"
    id: piscina_luzes_cobertura_pergolado
    pin: GPIO21
